version: '3.5'

services:
    converty:
        image: converty_img:latest
        container_name: converty_bot
        volumes:
            - ./source:/root/converty
            - ./config/converty_config.ini:/etc/converty_config.ini

    db:
        image: postgres
        container_name: "converty_db"
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=thoh7eTh
            - POSTGRES_DB=converty
